networks:
  frontend: # this network will be used for any other docker that need an access through the reverse proxy
    external: false
    name: frontend
  backend:

services:
  appsec-npm:
    container_name: npm-attachment
    image: 'ghcr.io/openappsec/nginx-proxy-manager-attachment:latest'
    ipc: host
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ./data/data:/data
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/appsec-logs:/ext/appsec-logs
      - ./data/appsec-config/local_policy.yaml:/ext/appsec/local_policy.yaml
    networks:
      - frontend
      - backend

  appsec-agent:
    container_name: appsec-agent
    image: 'ghcr.io/openappsec/agent:latest'
    ipc: host
    restart: unless-stopped
    environment:
      # adjust with your own email below
      - user_email=pymiguet@gmail.com
      - nginxproxymanager=true
      - autoPolicyLoad=true
    volumes:
      - ./data/appsec-config:/etc/cp/conf
      - ./data/appsec-data:/etc/cp/data
      - ./data/appsec-logs:/var/log/nano_agent
      - ./data/appsec-config/local_policy.yaml:/ext/appsec/local_policy.yaml
    command: /cp-nano-agent --standalone
    networks:
      - backend
