#!/bin/bash

# A script to perform incremental backups to another server using rsync
# Inspired by https://stackoverflow.com/questions/75977417/how-to-write-an-incremental-backup-script-using-rsync
# This backup has to be amnually launched on the client

set -o errexit
set -o nounset
set -o pipefail

readonly SOURCE_DIR="${HOME}"
readonly BACKUP_DIR="${HOME}/backups"
readonly DATETIME="$(date '+%Y-%m-%d_%H:%M:%S')"
readonly BACKUP_PATH="${BACKUP_DIR}/${DATETIME}"
readonly LATEST_LINK="${BACKUP_DIR}/latest"
readonly SERVER_NAME="pi@backup.mysite.me"
readonly SSH_PORT="22"

ssh $SERVER_NAME -p $SSH_PORT "mkdir -p ${BACKUP_DIR}"

sudo rsync -e "ssh -p ${SSH_PORT}" -avz --delete \
  "${SOURCE_DIR}/" \
  --exclude-from="backup-excludes.txt" \
  --link-dest "../latest" \
  "${SERVER_NAME}:/${BACKUP_PATH}"

ssh $SERVER_NAME -p $SSH_PORT "rm -rf ${LATEST_LINK}"
ssh $SERVER_NAME -p $SSH_PORT "ln -s ${BACKUP_PATH} ${LATEST_LINK}"
