version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - ./data:/config
      - ${TRANSMISSION_DOWNLOADS_FOLDER}:/downloads/complete # downloads are saved on a mounted samba share
      - ${TRANSMISSION_INCOMPLETE_FOLDER}:/downloads/incomplete # downloads are saved on a mounted samba share
    networks:
      - frontend
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    dns: # using this DNS to prevent some blocking with the actual ones
      - 8.8.8.8
      - 8.8.4.4
    labels:
      - io.portainer.accesscontrol.public
networks:
  frontend:
    driver: bridge
    external: true
